// <auto-generated />
using Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Migrations
{
    [DbContext(typeof(ShopikDbContext))]
    [Migration("20211105134500_Add_Seed_Init")]
    partial class Add_Seed_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Entity.Shop.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -1,
                            DisplayName = "Coca-Cola",
                            ImageUrl = "",
                            Price = 17m
                        },
                        new
                        {
                            Id = -2,
                            CategoryId = -2,
                            DisplayName = "Pilsner Urquell",
                            ImageUrl = "",
                            Price = 32m
                        },
                        new
                        {
                            Id = -3,
                            CategoryId = -3,
                            DisplayName = "3Bit",
                            ImageUrl = "",
                            Price = 13m
                        },
                        new
                        {
                            Id = -4,
                            CategoryId = -4,
                            DisplayName = "Bohemia tyčinky",
                            ImageUrl = "",
                            Price = 20m
                        },
                        new
                        {
                            Id = -5,
                            CategoryId = -5,
                            DisplayName = "Mana drink",
                            ImageUrl = "",
                            Price = 85m
                        });
                });

            modelBuilder.Entity("Entity.Shop.ShopItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopItemCategories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DisplayName = "Limonády"
                        },
                        new
                        {
                            Id = -2,
                            DisplayName = "Pivo"
                        },
                        new
                        {
                            Id = -3,
                            DisplayName = "Sladké"
                        },
                        new
                        {
                            Id = -4,
                            DisplayName = "Slané"
                        },
                        new
                        {
                            Id = -5,
                            DisplayName = "Zdravé"
                        });
                });

            modelBuilder.Entity("Entity.Shop.ShopItem", b =>
                {
                    b.HasOne("Entity.Shop.ShopItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
